#!/usr/bin/env python3
"""
Supplementary schematic: the four levels at which the statistical
surrogate for the LLM policy was evaluated.

Purely diagrammatic -- no measured data are plotted.  The only numeric
fact drawn is the stated 5.3% supported-field fraction for `intervals`.

Output: figures/si/figS_surrogate_logic_schematic.pdf
"""

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, FancyArrowPatch, FancyBboxPatch, Circle
from matplotlib.lines import Line2D

# --------------------------------------------------------------------------
# style
# --------------------------------------------------------------------------
plt.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Helvetica", "Arial"],
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "hatch.linewidth": 0.45,
        "text.usetex": False,
    }
)

INK = "#1a1a1a"
GREY = "#555555"
LGREY = "#b9b9b9"
RULE = "#d6d6d6"
BLUE = "#2f5d8a"          # acquisition fields
BLUE_F = "#dce5ef"
OVER = "#a3b8d0"          # overlap of the two field populations
RUST = "#a8552a"          # closed-loop fields
BOXED = "#c3c3c3"
BOXF = "#f6f6f4"
BAND = "#eef1f4"

FS_LETTER = 9.0
FS_TITLE = 8.0
FS_BODY = 7.0
FS_SMALL = 6.5
FS_TAKE = 7.5

W, H = 7.5, 3.2

fig = plt.figure(figsize=(W, H))
ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, W)
ax.set_ylim(0, H)
ax.set_aspect("equal")
ax.axis("off")


def txt(x, y, s, size=FS_BODY, ha="left", va="center", color=INK, weight="normal",
        style="normal", zorder=6):
    return ax.text(x, y, s, fontsize=size, ha=ha, va=va, color=color,
                   fontweight=weight, fontstyle=style, zorder=zorder)


def panel_head(xl, letter, title):
    txt(xl, 3.00, letter, size=FS_LETTER, weight="bold", va="baseline")
    txt(xl + 0.17, 3.00, title, size=FS_TITLE, va="baseline", color=INK)


def arrow(p0, p1, rad=0.0, color=INK, lw=0.8, ls="-"):
    a = FancyArrowPatch(p0, p1, arrowstyle="-|>", mutation_scale=7,
                        lw=lw, color=color, linestyle=ls,
                        connectionstyle=f"arc3,rad={rad}",
                        shrinkA=0, shrinkB=0, zorder=7,
                        joinstyle="miter")
    ax.add_patch(a)
    return a


# panel separators
for xs in (2.92, 5.08):
    ax.add_line(Line2D([xs, xs], [0.58, 3.06], color=RULE, lw=0.6, zorder=1))

# ==========================================================================
# PANEL a -- two field populations
# ==========================================================================
panel_head(0.12, "a", "Two field populations")

cA, cB = (0.98, 1.83), (2.10, 1.62)
eA_kw = dict(width=1.42, height=1.16, angle=0)
eB_kw = dict(width=1.34, height=1.08, angle=-14)

eA = Ellipse(cA, **eA_kw, facecolor=BLUE_F, edgecolor=BLUE, lw=0.9, zorder=2)
ax.add_patch(eA)

# hatched closed-loop cloud (drawn transparent so the overlap stays visible)
eB = Ellipse(cB, **eB_kw, facecolor="none", edgecolor=RUST, lw=1.0,
             hatch="///", zorder=4)
ax.add_patch(eB)

# intersection: clip a copy of A against B
eOv = Ellipse(cA, **eA_kw, facecolor=OVER, edgecolor="none", zorder=3)
ax.add_patch(eOv)
eOv.set_clip_path(eB)

txt(0.86, 1.94, "acquisition", size=FS_BODY, ha="center", color=INK)
txt(0.86, 1.79, "fields", size=FS_BODY, ha="center", color=INK)
txt(2.30, 1.72, "closed-loop", size=FS_BODY, ha="center", color=INK)
txt(2.30, 1.57, "fields", size=FS_BODY, ha="center", color=INK)

txt(0.14, 0.90, "(controlled sweeps)", size=FS_SMALL, ha="left", color=GREY)
txt(2.78, 0.90, "(generated by the interacting", size=FS_SMALL, ha="right",
    color=GREY)
txt(2.78, 0.76, "population)", size=FS_SMALL, ha="right", color=GREY)

# annotation arrows
txt(0.14, 2.79, "surrogate fitted here", size=FS_BODY, ha="left", color=BLUE)
arrow((0.62, 2.69), (0.90, 2.45), rad=-0.25, color=BLUE, lw=0.85)

txt(2.80, 2.79, "must predict here", size=FS_BODY, ha="right", color=RUST)
arrow((2.58, 2.68), (2.33, 2.02), rad=-0.16, color=RUST, lw=0.85)

# emphasise the non-overlapping part
txt(1.52, 0.66, "partial overlap only", size=FS_SMALL, ha="center",
    color=GREY, style="italic")
ax.add_line(Line2D([1.52, 1.57], [0.78, 1.52], color=LGREY, lw=0.6,
                   linestyle=(0, (2, 2)), zorder=2))

# ==========================================================================
# PANEL b -- two different tests
# ==========================================================================
panel_head(3.04, "b", "Two of the four levels")

BX0, BX1 = 3.04, 4.96


def testbox(y0, y1, head, lines, note, accent):
    ax.add_patch(
        FancyBboxPatch((BX0, y0), BX1 - BX0, y1 - y0,
                       boxstyle="round,pad=0,rounding_size=0.055",
                       facecolor=BOXF, edgecolor=BOXED, lw=0.7, zorder=2)
    )
    ax.add_line(Line2D([BX0 + 0.005, BX0 + 0.005], [y0 + 0.05, y1 - 0.05],
                       color=accent, lw=2.0, solid_capstyle="butt", zorder=3))
    txt(BX0 + 0.12, y1 - 0.14, head, size=FS_BODY, weight="bold", color=accent)
    yy = y1 - 0.32
    for ln in lines:
        txt(BX0 + 0.12, yy, ln, size=FS_BODY, color=INK)
        yy -= 0.155
    txt(BX0 + 0.12, yy + 0.02, note, size=FS_SMALL, color=GREY, style="italic")


testbox(1.98, 2.84, "COMPRESSIBILITY",
        ["held-out LLM responses on",
         "acquisition fields: does the",
         "surrogate beat the baseline?"],
        "grouped out-of-fold CV, by field", BLUE)

testbox(0.82, 1.68, "CLOSED-LOOP SUPPORT",
        ["closed-loop fields: are they",
         "inside the surrogate's",
         "supported region?"],
        "prerequisite for the prospective test", RUST)

arrow((3.34, 1.96), (3.34, 1.72), color=GREY, lw=0.8, ls=(0, (2.2, 1.8)))
txt(3.48, 1.90, "does not", size=FS_SMALL, color=GREY, style="italic")
txt(3.48, 1.78, "imply", size=FS_SMALL, color=GREY, style="italic")

# ==========================================================================
# PANEL c -- outcome per encoding
# ==========================================================================
panel_head(5.20, "c", "Outcome per encoding")

CX0, CX1 = 5.20, 7.38
ROWX = 5.20

txt(CX0, 2.63, "levels reached by each branch",
    size=FS_SMALL, ha="left", color=GREY, style="italic")
ax.add_line(Line2D([CX0, CX1], [2.52, 2.52], color=LGREY, lw=0.7, zorder=3))


def mark(x, y, ok):
    """small filled dot = pass, open dot = stop."""
    r = 0.036
    if ok:
        ax.add_patch(Circle((x, y), r, facecolor=BLUE, edgecolor=BLUE,
                            lw=0.7, zorder=5))
    else:
        ax.add_patch(Circle((x, y), r, facecolor="white", edgecolor=RUST,
                            lw=0.9, zorder=5))


# Each branch is described by the same three levels, in order. The fourth
# level, prospective transportability, is the last line of each block; it was
# reached only where closed-loop support held.
rows = [
    ("moments", 2.34, [
        (True, "compressibility: pass"),
        (True, "closed-loop support: pass after repair"),
        (True, "prospective evaluation: performed"),
    ]),
    ("centers", 1.62, [
        (True, "compressibility: pass"),
        (False, "closed-loop support: stop, no supported fields"),
        (False, "prospective evaluation: not performed"),
    ]),
    ("intervals", 0.90, [
        (True, "compressibility: pass"),
        (False, "closed-loop support: stop, 5.3% supported"),
        (False, "prospective evaluation: not performed"),
    ]),
]

for name, y, lines in rows:
    txt(ROWX, y, name, size=FS_BODY, ha="left", weight="bold")
    yy = y - 0.155
    for ok, label in lines:
        mark(ROWX + 0.07, yy, ok)
        txt(ROWX + 0.16, yy, label, size=FS_SMALL, ha="left",
            color=INK if ok else RUST)
        yy -= 0.145

# ==========================================================================
# takeaway band
# ==========================================================================
ax.add_patch(
    FancyBboxPatch((0.12, 0.08), 7.26, 0.33,
                   boxstyle="round,pad=0,rounding_size=0.06",
                   facecolor=BAND, edgecolor=LGREY, lw=0.6, zorder=2)
)
txt(W / 2.0, 0.245, "Cross-validation alone would accept all three "
    "encodings; only moments cleared closed-loop support and was evaluated "
    "prospectively.",
    size=FS_TAKE, ha="center", color=INK, zorder=6)

# --------------------------------------------------------------------------
outdir = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "figures", "si",
)
os.makedirs(outdir, exist_ok=True)
out = os.path.join(outdir, "figS_surrogate_logic_schematic.pdf")
fig.savefig(out, format="pdf")
plt.close(fig)
print("wrote", out, os.path.getsize(out), "bytes")
